### ISSUE TITLE
backup tool does not work with python 2.6 (AttributeError: 'module' object has no attribute 'check_output')

### ISSUE THREAD

**Issue by macosforgebot** [apple/ccs-calendarserver#350]
_mail@…_ originally submitted this as _[ticket:449](https://trac.calendarserver.org/ticket/449)_
-   **Cc:** _sagen_

---

Running the new export utility gives:

```
# ./tools/backup -f /etc/caldavd/caldavd.plist -v backup /root/back.up


Dumping data to /tmp/tmpoKViuv.dbdump
Executing: /usr/bin/pg_dump --username=caldav --clean --no-privileges --file=/tmp/tmpoKViuv.dbdump caldav
Traceback (most recent call last):
  File "./tools/backup", line 230, in <module>
    main()
  File "./tools/backup", line 168, in main
    dumpData(tmpPath, verbose=verbose)
  File "./tools/backup", line 79, in dumpData
    out = subprocess.check_output(cmdArgs, stderr=subprocess.STDOUT)
AttributeError: 'module' object has no attribute 'check_output'
```

According to https://github.com/rubik/pyg/issues/35 this was added with python 2.7.

**Comment by macosforgebot** [comment]
@wsanchez originally submitted this as _[comment:1:⁠ticket:449](https://trac.calendarserver.org/ticket/449#comment:1)_
-   **Status** changed from _new_ to _closed_
-   **Resolution** changed from to _Duplicate_

---

Dup of [#⁠432](https://trac.calendarserver.org/ticket/432)
